# Generated by Django 4.2.3 on 2023-07-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(verbose_name='published')),
                ('blog_content', models.TextField(max_length=1000)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('no_of_comments', models.IntegerField(default=0)),
            ],
        ),
    ]
